ggnn:
  hidden_dim: 512
  time_steps: [3, 1, 3, 1]
  residuals:
    1: [0]
    3: [0, 1]
  dropout_rate: 0.1
  add_type_bias: true
transformer:
  hidden_dim: 512
  ff_dim: 2048
  num_layers: 6
  attention_dim: 512
  num_heads: 8
  dropout_rate: 0.1
rnn:
  hidden_dim: 512
  num_layers: 2
  dropout_rate: 0.1
data:
  max_batch_size: 12500
  max_buffer_size: 50
  max_sequence_length: 512
  num_edge_types: 24
  valid_interval: 250000
  max_valid_samples: 25000
  max_token_length: 10
training:
  max_steps: 100
  print_freq: 25
  learning_rate: 0.0001
  model: "great"
